export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

//reset password
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

//forget password
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

// change language
export const LANGUAGE_CHANGE_SUCCESS = "LANGUAGE_CHANGE_SUCCESS";

// user
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_ERROR = "GET_ALL_USER_ERROR";
export const GET_ROLE_WISE_USER_SUCCESS = "GET_ROLE_WISE_USER_SUCCESS";
export const GET_ROLE_WISE_USER_ERROR = "GET_ROLE_WISE_USER_ERROR";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_ERROR = "DELETE_PROFILE_ERROR";
export const GET_USERS_PROFILE_SUCCESS = "GET_USERS_PROFILE_SUCCESS";
export const GET_USERS_PROFILE_ERROR = "GET_USERS_PROFILE_ERROR";
export const EDIT_USERS_PROFILE_SUCCESS = "EDIT_USERS_PROFILE_SUCCESS";
export const EDIT_USERS_PROFILE_ERROR = "EDIT_USERS_PROFILE_ERROR";
export const GET_STUDENT_ID_TO_GET_PARENT_DETAILS_SUCCESS =
  "GET_STUDENT_ID_TO_GET_PARENT_DETAILS_SUCCESS";
export const GET_STUDENT_ID_TO_GET_PARENT_DETAILS_ERROR =
  "GET_STUDENT_ID_TO_GET_PARENT_DETAILS_ERROR";
export const ID_TO_GET_USER_DETAILS_SUCCESS = "ID_TO_GET_USER_DETAILS_SUCCESS";
export const ID_TO_GET_USER_DETAILS_ERROR = "ID_TO_GET_USER_DETAILS_ERROR";

//tutor
export const GET_TUTOR_SUCCESS = "GET_TUTOR_SUCCESS";
export const GET_TUTOR_ERROR = "GET_TUTOR_ERROR";
export const GET_ALL_TUTOR_SESSION_SUCCESS = "GET_ALL_TUTOR_SESSION_SUCCESS";
export const GET_ALL_TUTOR_SESSION_ERROR = "GET_ALL_TUTOR_SESSION_ERROR";
export const GET_TUTOR_SESSION_BY_ID_SUCCESS =
  "GET_TUTOR_SESSION_BY_ID_SUCCESS";
export const GET_TUTOR_SESSION_BY_ID_ERROR = "GET_TUTOR_SESSION_BY_ID_ERROR";
export const ADD_TUTOR_SUCCESS = "ADD_TUTOR_SUCCESS";
export const ADD_TUTOR_ERROR = "ADD_TUTOR_ERROR";
export const EDIT_TUTOR_SUCCESS = "EDIT_TUTOR_SUCCESS";
export const EDIT_TUTOR_ERROR = "EDIT_TUTOR_ERROR";
export const DELETE_TUTOR_SUCCESS = "DELETE_TUTOR_SUCCESS";
export const DELETE_TUTOR_ERROR = "DELETE_TUTOR_ERROR";
export const ADD_COMPLETE_TUTOR_SESSION_SUCCESS =
  "ADD_COMPLETE_TUTOR_SESSION_SUCCESS";
export const ADD_COMPLETE_TUTOR_SESSION_ERROR =
  "ADD_COMPLETE_TUTOR_SESSION_ERROR";
export const GET_ALL_TUTOR_STUDENTS_SUCCESS = "GET_ALL_TUTOR_STUDENTS_SUCCESS";
export const GET_ALL_TUTOR_STUDENTS_ERROR = "GET_ALL_TUTOR_STUDENTS_ERROR";
export const GET_ALL_TUTOR_MY_STUDENTS_SUCCESS =
  "GET_ALL_TUTOR_MY_STUDENTS_SUCCESS";
export const GET_ALL_TUTOR_MY_STUDENTS_ERROR =
  "GET_ALL_TUTOR_MY_STUDENTS_ERROR";
export const GET_ALL_TUTOR_STUDENT_SESSION_BY_ID_SUCCESS =
  "GET_ALL_TUTOR_STUDENT_SESSION_BY_ID_SUCCESS";
export const GET_ALL_TUTOR_STUDENT_SESSION_BY_ID_ERROR =
  "GET_ALL_TUTOR_STUDENT_SESSION_BY_ID_ERROR";
export const GET_ALL_STUDENT_AND_PARENT_SUCCESS =
  "GET_ALL_STUDENT_AND_PARENT_SUCCESS";
export const GET_ALL_STUDENT_AND_PARENT_ERROR =
  "GET_ALL_STUDENT_AND_PARENT_ERROR";
export const GET_STUDENT_ALL_SESSION_WISE_SUBJECT_SUCCESS =
  "GET_STUDENT_ALL_SESSION_WISE_SUBJECT_SUCCESS";
export const GET_STUDENT_ALL_SESSION_WISE_SUBJECT_ERROR =
  "GET_STUDENT_ALL_SESSION_WISE_SUBJECT_ERROR";
export const GET_PARENT_ALL_STUDENT_SESSION_DETAILS_SUCCESS =
  "GET_PARENT_ALL_STUDENT_SESSION_DETAILS_SUCCESS";
export const GET_PARENT_ALL_STUDENT_SESSION_DETAILS_ERROR =
  "GET_PARENT_ALL_STUDENT_SESSION_DETAILS_ERROR";
export const GET_STUDENT_SESSION_DETAILS_SUCCESS =
  "GET_STUDENT_SESSION_DETAILS_SUCCESS";
export const GET_STUDENT_SESSION_DETAILS_ERROR =
  "GET_STUDENT_SESSION_DETAILS_ERROR";
export const GET_SINGLE_STUDENT_SESSION_DETAILS_SUCCESS =
  "GET_SINGLE_STUDENT_SESSION_DETAILS_SUCCESS";
export const GET_SINGLE_STUDENT_SESSION_DETAILS_ERROR =
  "GET_SINGLE_STUDENT_SESSION_DETAILS_ERROR";
export const EDIT_DELETE_SESSION_INFO_SUCCESS =
  "EDIT_DELETE_SESSION_INFO_SUCCESS";
export const EDIT_DELETE_SESSION_INFO_ERROR = "EDIT_DELETE_SESSION_INFO_ERROR";
export const GET_ALL_STUDENTS_TUTOR_SUCCESS = "GET_ALL_STUDENTS_TUTOR_SUCCESS";
export const GET_ALL_STUDENTS_TUTOR_ERROR = "GET_ALL_STUDENTS_TUTOR_ERROR";
export const GET_ALL_PARENT_STUDENT_SUCCESS = "GET_ALL_PARENT_STUDENT_SUCCESS";
export const GET_ALL_PARENT_STUDENT_ERROR = "GET_ALL_PARENT_STUDENT_ERROR";
export const GET_ALL_PARENT_STUDENT_SUBJECT_TO_FIND_TUTOR_ID_SUCCESS =
  "GET_ALL_PARENT_STUDENT_SUBJECT_TO_FIND_TUTOR_ID_SUCCESS";
export const GET_ALL_PARENT_STUDENT_SUBJECT_TO_FIND_TUTOR_ID_ERROR =
  "GET_ALL_PARENT_STUDENT_SUBJECT_TO_FIND_TUTOR_ID_ERROR";
export const GET_ALL_SUGGESTED_STUDENT_SUCCESS =
  "GET_ALL_SUGGESTED_STUDENT_SUCCESS";
export const GET_ALL_SUGGESTED_STUDENT_ERROR =
  "GET_ALL_SUGGESTED_STUDENT_ERROR";
export const GET_SUGGESTED_STUDENT_DETAILS_BY_ID_SUCCESS =
  "GET_SUGGESTED_STUDENT_DETAILS_BY_ID_SUCCESS";
export const GET_SUGGESTED_STUDENT_DETAILS_BY_ID_ERROR =
  "GET_SUGGESTED_STUDENT_DETAILS_BY_ID_ERROR";
// subject
export const GET_ALL_SUBJECT_SUCCESS = "GET_ALL_SUBJECT_SUCCESS";
export const GET_ALL_SUBJECT_ERROR = "GET_ALL_SUBJECT_ERROR";
export const GET_ALL_SUBJECT_BY_STUDENT_AND_TUTOR_ID_SUCCESS =
  "GET_ALL_SUBJECT_BY_STUDENT_AND_TUTOR_ID_SUCCESS";
export const GET_ALL_SUBJECT_BY_STUDENT_AND_TUTOR_ID_ERROR =
  "GET_ALL_SUBJECT_BY_STUDENT_AND_TUTOR_ID_ERROR";
export const GET_ALL_PARENT_STUDENT_SUBJECT_SUCCESS =
  "GET_ALL_PARENT_STUDENT_SUBJECT_SUCCESS";
export const GET_ALL_PARENT_STUDENT_SUBJECT_ERROR =
  "GET_ALL_PARENT_STUDENT_SUBJECT_ERROR";
// payment
// ************************ PARENT ****************************
export const ADD_CARD_PAYMENT_SUCCESS = "ADD_CARD_PAYMENT_SUCCESS";
export const ADD_CARD_PAYMENT_ERROR = "ADD_CARD_PAYMENT_ERROR";
export const GET_CARD_PAYMENT_SUCCESS = "GET_CARD_PAYMENT_SUCCESS";
export const GET_CARD_PAYMENT_ERROR = "GET_CARD_PAYMENT_ERROR";
export const EDIT_CARD_PAYMENT_SUCCESS = "EDIT_CARD_PAYMENT_SUCCESS";
export const EDIT_CARD_PAYMENT_ERROR = "EDIT_CARD_PAYMENT_ERROR";
export const DELETE_CARD_PAYMENT_SUCCESS = "DELETE_CARD_PAYMENT_SUCCESS";
export const DELETE_CARD_PAYMENT_ERROR = "DELETE_CARD_PAYMENT_ERROR";

// ************************ TUTOR ****************************
export const ADD_PAYMENT_DEDUCATIONS_SUCCESS =
  "ADD_PAYMENT_DEDUCATIONS_SUCCESS";
export const ADD_PAYMENT_DEDUCATIONS_ERROR = "ADD_PAYMENT_DEDUCATIONS_ERROR";
export const GET_ALL_PAYMENT_DEDUCATIONS_SUCCESS =
  "GET_ALL_PAYMENT_DEDUCATIONS_SUCCESS";
export const GET_ALL_PAYMENT_DEDUCATIONS_ERROR =
  "GET_ALL_PAYMENT_DEDUCATIONS_ERROR";

// notifications
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";
export const ADD_NOTIFICATION_SUCCESS = "ADD_NOTIFICATION_SUCCESS";
export const ADD_NOTIFICATION_ERROR = "ADD_NOTIFICATION_ERROR";
export const EDIT_NOTIFICATION_SUCCESS = "EDIT_NOTIFICATION_SUCCESS";
export const EDIT_NOTIFICATION_ERROR = "EDIT_NOTIFICATION_ERROR";

// follow up tutor
export const ADD_TUTOR_FOLLOW_UP_SUCCESS = "ADD_TUTOR_FOLLOW_UP_SUCCESS";
export const ADD_TUTOR_FOLLOW_UP_ERROR = "ADD_TUTOR_FOLLOW_UP_ERROR";
export const GET_TUTOR_FOLLOW_UP_SUCCESS = "GET_TUTOR_FOLLOW_UP_SUCCESS";
export const GET_TUTOR_FOLLOW_UP_ERROR = "GET_TUTOR_FOLLOW_UP_ERROR";
export const GET_ALL_TUTOR_STUDENT_FOLLOW_UP_REPORT_SUCCESS =
  "GET_ALL_TUTOR_STUDENT_FOLLOW_UP_REPORT_SUCCESS";
export const GET_ALL_TUTOR_STUDENT_FOLLOW_UP_REPORT_ERROR =
  "GET_ALL_TUTOR_STUDENT_FOLLOW_UP_REPORT_ERROR";

// ----- second tab -------------
export const GET_ALL_TUTOR_FOR_FOLLOW_UP_REPORT_SUCCESS =
  "GET_ALL_TUTOR_FOR_FOLLOW_UP_REPORT_SUCCESS";
export const GET_ALL_TUTOR_FOR_FOLLOW_UP_REPORT_ERROR =
  "GET_ALL_TUTOR_FOR_FOLLOW_UP_REPORT_ERROR";

// follow up student
export const ADD_STUDENT_FOLLOW_UP_SUCCESS = "ADD_STUDENT_FOLLOW_UP_SUCCESS";
export const ADD_STUDENT_FOLLOW_UP_ERROR = "ADD_STUDENT_FOLLOW_UP_ERROR";
export const GET_ALL_STUDENT_FOLLOW_UP_REPORT_WITH_DETAILS_SUCCESS =
  "GET_ALL_STUDENT_FOLLOW_UP_REPORT_WITH_DETAILS_SUCCESS";
export const GET_ALL_STUDENT_FOLLOW_UP_REPORT_WITH_DETAILS_ERROR =
  "GET_ALL_STUDENT_FOLLOW_UP_REPORT_WITH_DETAILS_ERROR";
export const GET_ALL_TUTOR_FOLLOW_UP_REPORT_WITH_DETAILS_SUCCESS =
  "GET_ALL_TUTOR_FOLLOW_UP_REPORT_WITH_DETAILS_SUCCESS";
export const GET_ALL_TUTOR_FOLLOW_UP_REPORT_WITH_DETAILS_ERROR =
  "GET_ALL_TUTOR_FOLLOW_UP_REPORT_WITH_DETAILS_ERROR";
export const GET_ALL_STUDENT_SUBJECT_DETAILS_SUCCESS =
  "GET_ALL_STUDENT_SUBJECT_DETAILS_SUCCESS";
export const GET_ALL_STUDENT_SUBJECT_DETAILS_ERROR =
  "GET_ALL_STUDENT_SUBJECT_DETAILS_ERROR";

// follow up parent
export const GET_ALL_PARENT_STUDENT_FOLLOW_UP_REPORT_SUCCESS =
  "GET_ALL_PARENT_STUDENT_FOLLOW_UP_REPORT_SUCCESS";
export const GET_ALL_PARENT_STUDENT_FOLLOW_UP_REPORT_ERROR =
  "GET_ALL_PARENT_STUDENT_FOLLOW_UP_REPORT_ERROR";
export const GET_ALL_STUDENT_TUTOR_FOLLOW_UP_REPORT_SUCCESS =
  "GET_ALL_STUDENT_TUTOR_FOLLOW_UP_REPORT_SUCCESS";
export const GET_ALL_STUDENT_TUTOR_FOLLOW_UP_REPORT_ERROR =
  "GET_ALL_STUDENT_TUTOR_FOLLOW_UP_REPORT_ERROR";
export const GET_PARENT_ALL_FOLLOW_UP_REPORT_SUCCESS =
  "GET_PARENT_ALL_FOLLOW_UP_REPORT_SUCCESS";
export const GET_PARENT_ALL_FOLLOW_UP_REPORT_ERROR =
  "GET_PARENT_ALL_FOLLOW_UP_REPORT_ERROR";
export const GET_PARENT_ALL_SUBJECT_DETAILS_SUCCESS =
  "GET_PARENT_ALL_SUBJECT_DETAILS_SUCCESS";
export const GET_PARENT_ALL_SUBJECT_DETAILS_ERROR =
  "GET_PARENT_ALL_SUBJECT_DETAILS_ERROR";
export const GET_ALL_PARENT_FOLLOW_UP_REPORT_WITH_DETAILS_SUCCESS =
  "GET_ALL_PARENT_FOLLOW_UP_REPORT_WITH_DETAILS_SUCCESS";
export const GET_ALL_PARENT_FOLLOW_UP_REPORT_WITH_DETAILS_ERROR =
  "GET_ALL_PARENT_FOLLOW_UP_REPORT_WITH_DETAILS_ERROR";
export const GET_PARENT_EVALUATE_OR_NOT_SUCCESS =
  "GET_PARENT_EVALUATE_OR_NOT_SUCCESS";
export const GET_PARENT_EVALUATE_OR_NOT_ERROR =
  "GET_PARENT_EVALUATE_OR_NOT_ERROR";

export const ADD_TUTOR_DOCUMENT_SUCCESS = "ADD_TUTOR_DOCUMENT_SUCCESS";
export const ADD_TUTOR_DOCUMENT_ERROR = "ADD_TUTOR_DOCUMENT_ERROR";
export const GET_ALL_TUTOR_DOCUMENT_SUCCESS = "GET_ALL_TUTOR_DOCUMENT_SUCCESS";
export const GET_ALL_TUTOR_DOCUMENT_ERROR = "GET_ALL_TUTOR_DOCUMENT_ERROR";
export const DELETE_TUTOR_DOCUMENT_SUCCESS = "DELETE_TUTOR_DOCUMENT_SUCCESS";
export const DELETE_TUTOR_DOCUMENT_ERROR = "DELETE_TUTOR_DOCUMENT_ERROR";
export const UPDATE_UNIVERSICTY_TUTOR_DOCUMENT_SUCCESS =
  "UPDATE_UNIVERSICTY_TUTOR_DOCUMENT_SUCCESS";
export const UPDATE_UNIVERSICTY_TUTOR_DOCUMENT_ERROR =
  "UPDATE_UNIVERSICTY_TUTOR_DOCUMENT_ERROR";
export const UPDATE_ALL_TUTOR_DOCUMENT_SUCCESS =
  "UPDATE_ALL_TUTOR_DOCUMENT_SUCCESS";
export const UPDATE_ALL_TUTOR_DOCUMENT_ERROR =
  "UPDATE_ALL_TUTOR_DOCUMENT_ERROR";

// Platefrom Evaluations
export const ADD_PLATEFROM_EVALUATION_SUCCESS =
  "ADD_PLATEFROM_EVALUATION_SUCCESS";
export const ADD_PLATEFROM_EVALUATION_ERROR = "ADD_PLATEFROM_EVALUATION_ERROR";
export const GET_PLATEFROM_EVALUATION_SUCCESS =
  "GET_PLATEFROM_EVALUATION_SUCCESS";
export const GET_PLATEFROM_EVALUATION_ERROR = "GET_PLATEFROM_EVALUATION_ERROR";

// send notification
export const SEND_SESSION_NOTIFICATION_SUCCESS =
  "SEND_SESSION_NOTIFICATION_SUCCESS";
export const SEND_SESSION_NOTIFICATION_ERROR =
  "SEND_SESSION_NOTIFICATION_ERROR";
export const SEND_ALERT_SESSION_NOTIFICATION_SUCCESS =
  "SEND_ALERT_SESSION_NOTIFICATION_SUCCESS";
export const SEND_ALERT_SESSION_NOTIFICATION_ERROR =
  "SEND_ALERT_SESSION_NOTIFICATION_ERROR";
export const GET_SESSION_NOTIFICATION_SUCCESS =
  "GET_SESSION_NOTIFICATION_SUCCESS";
export const GET_SESSION_NOTIFICATION_ERROR = "GET_SESSION_NOTIFICATION_ERROR";
export const GET_NOTIFICATION_SESSION_INFO_SUCCESS =
  "GET_NOTIFICATION_SESSION_INFO_SUCCESS";
export const GET_NOTIFICATION_SESSION_INFO_ERROR =
  "GET_NOTIFICATION_SESSION_INFO_ERROR";
export const UPDATE_REFUSER_SESSION_SUCCESS = "UPDATE_REFUSER_SESSION_SUCCESS";
export const UPDATE_REFUSER_SESSION_ERROR = "UPDATE_REFUSER_SESSION_ERROR";
export const CLOSE_ALERT_SUCCESS = "CLOSE_ALERT_SUCCESS";
export const CLOSE_ALERT_ERROR = "CLOSE_ALERT_ERROR";
export const READ_SEND_REQUEST_SUCCESS = "READ_SEND_REQUEST_SUCCESS";
export const READ_SEND_REQUEST_ERROR = "READ_SEND_REQUEST_ERROR";
export const READ_SEND_NOTIFICATION_TO_DO_LIST_SUCCESS =
  "READ_SEND_NOTIFICATION_TO_DO_LIST_SUCCESS";
export const READ_SEND_NOTIFICATION_TO_DO_LIST_ERROR =
  "READ_SEND_NOTIFICATION_TO_DO_LIST_ERROR";

//get document by document name
export const GET_DOCUMENT_BY_NAME_SUCCESS = "GET_DOCUMENT_BY_NAME_SUCCESS";
export const GET_DOCUMENT_BY_NAME_ERROR = "GET_DOCUMENT_BY_NAME_ERROR";

// student dashboard
export const GET_STUDENT_IN_TUTOR_SESSION_DETAILS_SUCCESS =
  "GET_STUDENT_IN_TUTOR_SESSION_DETAILS_SUCCESS";
export const GET_STUDENT_IN_TUTOR_SESSION_DETAILS_ERROR =
  "GET_STUDENT_IN_TUTOR_SESSION_DETAILS_ERROR";
export const ADD_LESSIN_SPACE_SESSION_END_SUCCESS =
  "ADD_LESSIN_SPACE_SESSION_END_SUCCESS";
export const ADD_LESSIN_SPACE_SESSION_END_ERROR =
  "ADD_LESSIN_SPACE_SESSION_END_ERROR";
export const GET_LESSIN_SPACE_SESSION_END_SUCCESS =
  "GET_LESSIN_SPACE_SESSION_END_SUCCESS";
export const GET_LESSIN_SPACE_SESSION_END_ERROR =
  "GET_LESSIN_SPACE_SESSION_END_ERROR";
export const GET_STUDENT_TUTOR_DETAILS_SUCCESS =
  "GET_STUDENT_TUTOR_DETAILS_SUCCESS";
export const GET_STUDENT_TUTOR_DETAILS_ERROR =
  "GET_STUDENT_TUTOR_DETAILS_ERROR";
export const GET_STUDENT_STATISTICS_SUCCESS = "GET_STUDENT_STATISTICS_SUCCESS";
export const GET_STUDENT_STATISTICS_ERROR = "GET_STUDENT_STATISTICS_ERROR";
export const GET_TO_DO_LIST_SUCCESS = "GET_TO_DO_LIST_SUCCESS";
export const GET_TO_DO_LIST_ERROR = "GET_TO_DO_LIST_ERROR";
export const READ_TO_DO_LIST_SUCCESS = "READ_TO_DO_LIST_SUCCESS";
export const READ_TO_DO_LIST_ERROR = "READ_TO_DO_LIST_ERROR";
export const READ_TO_DO_LIST_FROM_NOTIFICATIONS_SUCCESS =
  "READ_TO_DO_LIST_FROM_NOTIFICATIONS_SUCCESS";
export const READ_TO_DO_LIST_FROM_NOTIFICATIONS_ERROR =
  "READ_TO_DO_LIST_FROM_NOTIFICATIONS_ERROR";
export const READ_SESSION_DRAFT_SUCCESS = "READ_SESSION_DRAFT_SUCCESS";
export const READ_SESSION_DRAFT_ERROR = "READ_SESSION_DRAFT_ERROR";
export const GET_SESSION_ID_TO_TO_DO_LIST_SUCCESS =
  "GET_SESSION_ID_TO_TO_DO_LIST_SUCCESS";
export const GET_SESSION_ID_TO_TO_DO_LIST_ERROR =
  "GET_SESSION_ID_TO_TO_DO_LIST_ERROR";
export const GET_ALL_CURRENTY_WEEK_SESION_SUCCESS =
  "GET_ALL_CURRENTY_WEEK_SESION_SUCCESS";
export const GET_ALL_CURRENTY_WEEK_SESION_ERROR =
  "GET_ALL_CURRENTY_WEEK_SESION_ERROR";
export const GET_ALL_TODAY_SESSION_SUCCESS = "GET_ALL_TODAY_SESSION_SUCCESS";
export const GET_ALL_TODAY_SESSION_ERROR = "GET_ALL_TODAY_SESSION_ERROR";

// admin
// get all tutor
export const GET_USER_IN_ALL_TUTOR_SUCCESS = "GET_SUSER_IN_ALL_TUTOR_SUCCESS";
export const GET_USER_IN_ALL_TUTOR_ERROR = "GET_USER_IN_ALL_TUTOR_ERROR";

// get all parent
export const GET_USER_IN_ALL_PARENT_SUCCESS = "GET_SUSER_IN_ALL_PARENT_SUCCESS";
export const GET_USER_IN_ALL_PARENT_ERROR = "GET_USER_IN_ALL_PARENT_ERROR";

// get all student
export const GET_USER_IN_ALL_STUDENT_SUCCESS =
  "GET_SUSER_IN_ALL_STUDENT_SUCCESS";
export const GET_USER_IN_ALL_STUDENT_ERROR = "GET_USER_IN_ALL_STUDENT_ERROR";

// lesson space Lecture
export const GET_LESSON_SPACE_DEMO_LECTURE_SUCCESS =
  "GET_LESSON_SPACE_DEMO_LECTURE_SUCCESS";
export const GET_LESSON_SPACE_DEMO_LECTURE_ERROR =
  "GET_LESSON_SPACE_DEMO_LECTURE_ERROR";
export const GET_LESSON_SPACE_TUTOR_LECTURE_SUCCESS =
  "GET_LESSON_SPACE_TUTOR_LECTURE_SUCCESS";
export const GET_LESSON_SPACE_TUTOR_LECTURE_ERROR =
  "GET_LESSON_SPACE_TUTOR_LECTURE_ERROR";
export const GET_LESSON_SPACE_STUDENT_LECTURE_SUCCESS =
  "GET_LESSON_SPACE_STUDENT_LECTURE_SUCCESS";
export const GET_LESSON_SPACE_STUDENT_LECTURE_ERROR =
  "GET_LESSON_SPACE_STUDENT_LECTURE_ERROR";

// my school levels
export const GET_MY_SCHOOL_LEVELS_SUCCESS = "GET_MY_SCHOOL_LEVELS_SUCCESS";
export const GET_MY_SCHOOL_LEVELS_ERROR = "GET_MY_SCHOOL_LEVELS_ERROR";
export const GET_MY_SCHOOL_LEVEL_SUBJECTS_SUCCESS =
  "GET_MY_SCHOOL_LEVEL_SUBJECTS_SUCCESS";
export const GET_MY_SCHOOL_LEVEL_SUBJECTS_ERROR =
  "GET_MY_SCHOOL_LEVEL_SUBJECTS_ERROR";
export const GET_ALL_SCHOOL_LEVEL_SUBJECTS_SUCCESS =
  "GET_ALL_SCHOOL_LEVEL_SUBJECTS_SUCCESS";
export const GET_ALL_SCHOOL_LEVEL_SUBJECTS_ERROR =
  "GET_ALL_SCHOOL_LEVEL_SUBJECTS_ERROR";
export const GET_MATCHED_STUDENTS_SUCCESS = "GET_MATCHED_STUDENTS_SUCCESS";
export const GET_MATCHED_STUDENTS_ERROR = "GET_MATCHED_STUDENTS_ERROR";
export const GET_STUDENT_MATCHED_TUTOR_SUCCESS =
  "GET_STUDENT_MATCHED_TUTOR_SUCCESS";
export const GET_STUDENT_MATCHED_TUTOR_ERROR =
  "GET_STUDENT_MATCHED_TUTOR_ERROR";
export const ACCEPTED_MATCHED_SUCCESS = "ACCEPTED_MATCHED_SUCCESS";
export const ACCEPTED_MATCHED_ERROR = "ACCEPTED_MATCHED_ERROR";
