import Head from "next/head";
import withAuth from "./authRouter";

const Main = () => {
  return (
    <>
      <Head>
        {/* <title>Succes Scolaire</title> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel='icon' type='image/x-icon' href='' /> */}
      </Head>
    </>
  );
};

export default withAuth(Main);
