import {
  RoleEntity,
  UserEntity,
  TutorSessionEntity,
  TutorStudentEntity,
  TutorDocumentEntity,
  StudentAttendanceEntity,
  ChatEntity,
  ChatMessageEntity,
  NotificationSettingEntity,
  SubjectEntity,
  StripeCardEntity,
  CompleteSessionEntity,
  TutorSessionDraftEntity,
  PaymentDeductionEntity,
  TutorFollowUpEntity,
  StudentParentFollowUpEntity,
  PlateformEvaluationEntity,
  NotificationEntity,
  TutorSubjectEntity,
  StudentSubjectEntity,
  StudentProgramEntity,
  UserProfileEntity,
  LessonSpaceEntity,
  ToDoEntity,
  MySchoolLevelsEntity,
  MySchoolLevelSubjectsEntity,
  TutorStudentMatchEntity,
  TutorStudentMatchDraftEntity,
} from 'src/entities';

export default () => ({
  port: parseInt(process.env.BACKEND_PORT, 10) || 4000,
  jwt: {
    secretOrPrivateKey: process.env.JWT_SECRET,
    signOptions: {
      expiresIn: process.env.JWT_EXPIRES,
    },
  },
  database: {
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    entities: [
      RoleEntity,
      UserEntity,
      TutorSessionEntity,
      TutorStudentEntity,
      TutorDocumentEntity,
      StudentAttendanceEntity,
      NotificationSettingEntity,
      ChatEntity,
      ChatMessageEntity,
      SubjectEntity,
      StripeCardEntity,
      CompleteSessionEntity,
      TutorSessionDraftEntity,
      PaymentDeductionEntity,
      TutorFollowUpEntity,
      StudentParentFollowUpEntity,
      PlateformEvaluationEntity,
      NotificationEntity,
      TutorSubjectEntity,
      StudentSubjectEntity,
      StudentProgramEntity,
      UserProfileEntity,
      LessonSpaceEntity,
      ToDoEntity,
      MySchoolLevelsEntity,
      MySchoolLevelSubjectsEntity,
      TutorStudentMatchEntity,
      TutorStudentMatchDraftEntity,
    ],
    // entities: [__dirname + '/../**/*.entity.{js,ts}'],
    synchronize: process.env.DB_SYNCRONIZE === 'true',
    logging: process.env.DB_LOGGING === 'false',
    extra: {
      charset: 'utf8mb4_unicode_ci',
    },
  },
});
